name: .NET Build and Push Nuget

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1
      - uses: actions/checkout@master
      - uses: greenygh0st/net-proj-release-version@v2
        with:
          # path to the .csproj file
          PROJ_FILE: CLIProgram/CLIProgram.csproj
      - run: echo Building CLIProgram Version ${{ steps.get_version.outputs.RELEASE_VERSION }}
      - run: nuget restore CLIProgram.sln
      - run: msbuild CLIProgram.sln /p:Configuration=Release
      - uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CLIProgram/CLIProgram.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
